### ISSUE TITLE
exiting jar3d no reason.

### ISSUE THREAD

**Issue by MyraBaba** [brainqub3/jar3d_meta_expert#25]
Here the output of last logs..

> 2024-08-15 01:14:59 - https://google.serper.dev:443 "POST /search HTTP/11" 200 4270
DEBUG    2024-08-15 01:14:59 - https://google.serper.dev:443 "POST /search HTTP/11" 200 4270
DEBUG    2024-08-15 01:14:59 - https://google.serper.dev:443 "POST /search HTTP/11" 200 4270
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
        
bc@bc ~/Projects/meta_expertV2
 %
bc@bc ~/Projects/meta_expertV2
 %
bc@bc ~/Projects/meta_expertV2
 %
 
 
 its exits all the time...

**Comment by john-adeojo** [comment]
Which model are you using?

**Comment by john-adeojo** [comment]
The most recent commit uses Docker to get up and running with Jar3d. The approach should cause less errors, please give it a try and let me know how it goes.
